id: P118FAAF7
initial_creation_type: input
source_metadata:
  title: Smṛtijñānakīrti
  language: en
  description: 'Texts by and about the famous 11th-century Indian paṇḍita Smṛtijñānakīrti
    (dran pa''i ye shes grags pa):'
  volume:
    940a12dfdc684319920a0fa941cf8ad1:
      title: 'Great Treasury of Siddhis: A Guru Yoga of Paṇchen Smṛti'
      parent: Guru Yoga
    7511c8ff2b11416e801ad0a2630e548e:
      title: 'Intensely Brilliant Wisdom: In Praise of the Great Elder Smṛtijñāna'
      parent: Praise
    d2e1d6aa76454cec87793db6126bea0c:
      title: Prayer to Smṛtijñānakīrti
      parent: Prayers
created_at: '2022-03-01T02:24:30.276722'
last_modified_at: '2022-03-01T02:24:30.276728'
